backend:
  name: github
  repo: Emrahsahin07/terrabi
  branch: main

media_folder: "assets/images/products"
public_folder: "/assets/images/products"

media_library:
  name: "default"

collections:
  - name: "products"
    label: "Products"
    folder: "_data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Nuts", "Beans", "Legumes", "Rice", "Grains", "Dried Fruits"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
